version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5430:5430"
    environment:
      POSTGRES_DB: theater
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"